module.exports = function(d) {
var str = '<!doctype html>'
+ '<html>'
	+ '<head>'
		+ '<meta charset="utf-8">'
		+ '<meta name="viewport" content="width=device-width, initial-scale=1"/>'
		+ '<meta name="description" content="' + d.name + ' - by Idris GIS online tools"/>'
		+ '<meta name="keywords" content="' + d.keywords + ', Idris maps">'  
		+ '<title>' + d.name + '</title>'
  + '<link rel="stylesheet" href="' + d.link.leafletCss + '">'
  + '<link rel="stylesheet" href="' + d.link.leafletDrawCss + '">'
  + '<link rel="stylesheet" href="' + d.link.css + '">'
		+ '<script src="' + d.link.leafletJs + '"></script>'
		+ '<script src="' + d.link.leafletDrawJs + '"></script>'
	+ '</head>'
	+ '<body>'
		+ '<div id="header">'
			+ '<a id="back" href="' + d.link.back + '">'
				+ '<img src="../img/logo_fond_fonce.png" alt="Idris maps"/>'
			+ '</a>'
		+ '</div>'
		+ '<div id="map"></div>'
		+ '<script src="script.min.js"></script>'
	+ '</body>'
+ '</html>'

return str
}
